// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9X2sCT3hCGDKeqN4eE9hatEopSJdk30Y',
    appId: '1:164473088789:web:56099e76d3d9787102971c',
    messagingSenderId: '164473088789',
    projectId: 'flutterfire-db-2d256',
    authDomain: 'flutterfire-db-2d256.firebaseapp.com',
    storageBucket: 'flutterfire-db-2d256.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0SvDza2As6gynZx-upwAUcp-s2pG6rs',
    appId: '1:164473088789:android:0e941fb4e240562302971c',
    messagingSenderId: '164473088789',
    projectId: 'flutterfire-db-2d256',
    storageBucket: 'flutterfire-db-2d256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0S4V_HKy-UEPQt0SrmIoYkQb7YmX5WM',
    appId: '1:164473088789:ios:4e9608ce54845ede02971c',
    messagingSenderId: '164473088789',
    projectId: 'flutterfire-db-2d256',
    storageBucket: 'flutterfire-db-2d256.appspot.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0S4V_HKy-UEPQt0SrmIoYkQb7YmX5WM',
    appId: '1:164473088789:ios:4e9608ce54845ede02971c',
    messagingSenderId: '164473088789',
    projectId: 'flutterfire-db-2d256',
    storageBucket: 'flutterfire-db-2d256.appspot.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9X2sCT3hCGDKeqN4eE9hatEopSJdk30Y',
    appId: '1:164473088789:web:18e4e429caa16c8802971c',
    messagingSenderId: '164473088789',
    projectId: 'flutterfire-db-2d256',
    authDomain: 'flutterfire-db-2d256.firebaseapp.com',
    storageBucket: 'flutterfire-db-2d256.appspot.com',
  );
}
